// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alexGoLyceum/calculator-service/orchestrator/internal/transport/grpc/proto (interfaces: OrchestratorService_AssignTasksServer)
//
// Generated by this command:
//
//	mockgen -destination=orchestrator/mocks/stream_mock.go -package=mocks github.com/alexGoLyceum/calculator-service/orchestrator/internal/transport/grpc/proto OrchestratorService_AssignTasksServer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	proto "github.com/alexGoLyceum/calculator-service/orchestrator/internal/transport/grpc/proto"
	gomock "go.uber.org/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockOrchestratorService_AssignTasksServer is a mock of OrchestratorService_AssignTasksServer interface.
type MockOrchestratorService_AssignTasksServer[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockOrchestratorService_AssignTasksServerMockRecorder[Res]
	isgomock struct{}
}

// MockOrchestratorService_AssignTasksServerMockRecorder is the mock recorder for MockOrchestratorService_AssignTasksServer.
type MockOrchestratorService_AssignTasksServerMockRecorder[Res any] struct {
	mock *MockOrchestratorService_AssignTasksServer[Res]
}

// NewMockOrchestratorService_AssignTasksServer creates a new mock instance.
func NewMockOrchestratorService_AssignTasksServer[Res any](ctrl *gomock.Controller) *MockOrchestratorService_AssignTasksServer[Res] {
	mock := &MockOrchestratorService_AssignTasksServer[Res]{ctrl: ctrl}
	mock.recorder = &MockOrchestratorService_AssignTasksServerMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrchestratorService_AssignTasksServer[Res]) EXPECT() *MockOrchestratorService_AssignTasksServerMockRecorder[Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockOrchestratorService_AssignTasksServer[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockOrchestratorService_AssignTasksServerMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockOrchestratorService_AssignTasksServer[Res])(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockOrchestratorService_AssignTasksServer[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockOrchestratorService_AssignTasksServerMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockOrchestratorService_AssignTasksServer[Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockOrchestratorService_AssignTasksServer[Res]) Send(arg0 *proto.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockOrchestratorService_AssignTasksServerMockRecorder[Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockOrchestratorService_AssignTasksServer[Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockOrchestratorService_AssignTasksServer[Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockOrchestratorService_AssignTasksServerMockRecorder[Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockOrchestratorService_AssignTasksServer[Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockOrchestratorService_AssignTasksServer[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockOrchestratorService_AssignTasksServerMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockOrchestratorService_AssignTasksServer[Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockOrchestratorService_AssignTasksServer[Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockOrchestratorService_AssignTasksServerMockRecorder[Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockOrchestratorService_AssignTasksServer[Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockOrchestratorService_AssignTasksServer[Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockOrchestratorService_AssignTasksServerMockRecorder[Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockOrchestratorService_AssignTasksServer[Res])(nil).SetTrailer), arg0)
}
