// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.9
// source: orchestrator/internal/transport/grpc/orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignTasksRequest) Reset() {
	*x = AssignTasksRequest{}
	mi := &file_orchestrator_internal_transport_grpc_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignTasksRequest) ProtoMessage() {}

func (x *AssignTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_internal_transport_grpc_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignTasksRequest.ProtoReflect.Descriptor instead.
func (*AssignTasksRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDescGZIP(), []int{0}
}

type SubmitTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Result        float64                `protobuf:"fixed64,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskRequest) Reset() {
	*x = SubmitTaskRequest{}
	mi := &file_orchestrator_internal_transport_grpc_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskRequest) ProtoMessage() {}

func (x *SubmitTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_internal_transport_grpc_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitTaskRequest) Descriptor() ([]byte, []int) {
	return file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *SubmitTaskRequest) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

type SubmitTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTaskResponse) Reset() {
	*x = SubmitTaskResponse{}
	mi := &file_orchestrator_internal_transport_grpc_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTaskResponse) ProtoMessage() {}

func (x *SubmitTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_internal_transport_grpc_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitTaskResponse) Descriptor() ([]byte, []int) {
	return file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDescGZIP(), []int{2}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExpressionId  string                 `protobuf:"bytes,2,opt,name=expression_id,json=expressionId,proto3" json:"expression_id,omitempty"`
	Arg1Num       float64                `protobuf:"fixed64,3,opt,name=arg1_num,json=arg1Num,proto3" json:"arg1_num,omitempty"`
	Arg2Num       float64                `protobuf:"fixed64,4,opt,name=arg2_num,json=arg2Num,proto3" json:"arg2_num,omitempty"`
	Operator      string                 `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	OperationTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	FinalTask     bool                   `protobuf:"varint,7,opt,name=final_task,json=finalTask,proto3" json:"final_task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_orchestrator_internal_transport_grpc_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_orchestrator_internal_transport_grpc_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetExpressionId() string {
	if x != nil {
		return x.ExpressionId
	}
	return ""
}

func (x *Task) GetArg1Num() float64 {
	if x != nil {
		return x.Arg1Num
	}
	return 0
}

func (x *Task) GetArg2Num() float64 {
	if x != nil {
		return x.Arg2Num
	}
	return 0
}

func (x *Task) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *Task) GetOperationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OperationTime
	}
	return nil
}

func (x *Task) GetFinalTask() bool {
	if x != nil {
		return x.FinalTask
	}
	return false
}

var File_orchestrator_internal_transport_grpc_orchestrator_proto protoreflect.FileDescriptor

const file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDesc = "" +
	"\n" +
	"7orchestrator/internal/transport/grpc/orchestrator.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12AssignTasksRequest\"L\n" +
	"\x11SubmitTaskRequest\x12\x1f\n" +
	"\x04task\x18\x01 \x01(\v2\v.proto.TaskR\x04task\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x01R\x06result\"\x14\n" +
	"\x12SubmitTaskResponse\"\xef\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rexpression_id\x18\x02 \x01(\tR\fexpressionId\x12\x19\n" +
	"\barg1_num\x18\x03 \x01(\x01R\aarg1Num\x12\x19\n" +
	"\barg2_num\x18\x04 \x01(\x01R\aarg2Num\x12\x1a\n" +
	"\boperator\x18\x05 \x01(\tR\boperator\x12A\n" +
	"\x0eoperation_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\roperationTime\x12\x1d\n" +
	"\n" +
	"final_task\x18\a \x01(\bR\tfinalTask2\x91\x01\n" +
	"\x13OrchestratorService\x127\n" +
	"\vAssignTasks\x12\x19.proto.AssignTasksRequest\x1a\v.proto.Task0\x01\x12A\n" +
	"\n" +
	"SubmitTask\x12\x18.proto.SubmitTaskRequest\x1a\x19.proto.SubmitTaskResponseB.Z,./orchestrator/internal/transport/grpc/protob\x06proto3"

var (
	file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDescOnce sync.Once
	file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDescData []byte
)

func file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDescGZIP() []byte {
	file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDescOnce.Do(func() {
		file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDesc), len(file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDesc)))
	})
	return file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDescData
}

var file_orchestrator_internal_transport_grpc_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_orchestrator_internal_transport_grpc_orchestrator_proto_goTypes = []any{
	(*AssignTasksRequest)(nil),    // 0: proto.AssignTasksRequest
	(*SubmitTaskRequest)(nil),     // 1: proto.SubmitTaskRequest
	(*SubmitTaskResponse)(nil),    // 2: proto.SubmitTaskResponse
	(*Task)(nil),                  // 3: proto.Task
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_orchestrator_internal_transport_grpc_orchestrator_proto_depIdxs = []int32{
	3, // 0: proto.SubmitTaskRequest.task:type_name -> proto.Task
	4, // 1: proto.Task.operation_time:type_name -> google.protobuf.Timestamp
	0, // 2: proto.OrchestratorService.AssignTasks:input_type -> proto.AssignTasksRequest
	1, // 3: proto.OrchestratorService.SubmitTask:input_type -> proto.SubmitTaskRequest
	3, // 4: proto.OrchestratorService.AssignTasks:output_type -> proto.Task
	2, // 5: proto.OrchestratorService.SubmitTask:output_type -> proto.SubmitTaskResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_orchestrator_internal_transport_grpc_orchestrator_proto_init() }
func file_orchestrator_internal_transport_grpc_orchestrator_proto_init() {
	if File_orchestrator_internal_transport_grpc_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDesc), len(file_orchestrator_internal_transport_grpc_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orchestrator_internal_transport_grpc_orchestrator_proto_goTypes,
		DependencyIndexes: file_orchestrator_internal_transport_grpc_orchestrator_proto_depIdxs,
		MessageInfos:      file_orchestrator_internal_transport_grpc_orchestrator_proto_msgTypes,
	}.Build()
	File_orchestrator_internal_transport_grpc_orchestrator_proto = out.File
	file_orchestrator_internal_transport_grpc_orchestrator_proto_goTypes = nil
	file_orchestrator_internal_transport_grpc_orchestrator_proto_depIdxs = nil
}
